### ISSUE TITLE
Pretrained=True does not work in Wav2vec.

### ISSUE THREAD

**Issue by Harry24k** [shangeth/wavencoder#10]
Here is another error in wav2vec.

https://github.com/shangeth/wavencoder/blob/6874c6738f37bf04c8105bf6839e495848196a44/wavencoder/models/wav2vec.py#L217-L221

In the above code, pretrained_dict becomes an empty dict `{}` because there is no intersection between `pretrained_dict.state_dict()` and `feature_extractor.state_dict()`.

How about this:

```
pretrained_dict = cp['model']
model_dict = self.state_dict()
pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
model_dict.update(pretrained_dict) 
self.load_state_dict(model_dict)
```

Thanks!

**Comment by shangeth** [comment]
Hi @Harry24k 

Check the latest push. 
Hope the issue is solved.

Thanks for pointing the issue.
