### ISSUE TITLE
wav2vec2 import?

### ISSUE THREAD

**Issue by abnerLing** [shangeth/wavencoder#16]
Am I importing wav2vec2 incorrectly?

I simply copied the same code for wav2vec, but I get the below error? I just pip installed today.
```
Installing collected packages: wavencoder
Successfully installed wavencoder-0.1.2
```
```
import torch
import wavencoder

x = torch.randn(1, 16000) # [1, 16000]
encoder = wavencoder.models.Wav2Vec2(model_type='base', pretrained=True)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wavencoder.models' has no attribute 'Wav2Vec2'
```

**Comment by shangeth** [comment]
Hi @abnerLing ,
The pip version is not yet updated, I will update it soon.

**Comment by shangeth** [comment]
Hi @abnerLing ,
I have updated the pip repo.

check this notebook - https://colab.research.google.com/drive/1Vem1YNm2crVHRHDfPzfNzoA5-uTCQX_N?usp=sharing

**Comment by abnerLing** [comment]
Thank you very much! I appreciate your help.
