### ISSUE TITLE
Cuda Device

### ISSUE THREAD

**Issue by Harry24k** [shangeth/wavencoder#9]
Hi, there is a cuda device problem when I use torch.cuda.set_device.

Code is here:
https://github.com/shangeth/wavencoder/blob/6874c6738f37bf04c8105bf6839e495848196a44/wavencoder/models/wav2vec.py#L148-L151

Could it be okay to change it to:
```
class Wav2Vec(nn.Module):
    def __init__(self, pretrained=True, pretrained_path=None, device=torch.device("cpu")):
        super().__init__()
        self.device = device
```

This package helps me a lot.

Thank you.

**Comment by shangeth** [comment]
Oh, yes this needs to be done. The package right now is in the basic building phase and I will start actively working on this in few days. 
Feel feel to add issues/new features recommendations/PR, I will start working on these soon. 
Thank you.

**Comment by shangeth** [comment]
Updated wav2vec, sincnet, rawnet
